### ISSUE TITLE
Failed to build on wsl2

### ISSUE THREAD

**Issue by yliam73** [psyq321/PowerMonkey#4]
[-Werror=unknown-pragmas] and
error: implicit declaration of function ‘__cpuid’ [-Werror=implicit-function-declaration]

I think I may be using the wrong gcc version to compile, I followed the instructions on the edk2 for linux compilations. I also tried to compile it using gcc7

**Comment by alanpi** [comment]
iam getting the same error with vm ubuntu 16.04 and gcc 5.4. Everything builds without any problem only powermonkey getting an error

**Comment by psyq321** [comment]
PowerMonkey Release 0.1.9 adds support for building with Linux/WSL2 + Clang (edk2 toolchain: CLANGDWARF)

I did not test with the gcc, but I suppose it shall work (unless something else is wrong) since clang also struggled with the MSVC-style __cpuid intrinsic. This has been replaced with our own implementation.
